// lib/shared/itemDefinitions.ts

import type { ItemDefinition } from "./itemTypes.js";
import { rollItemStats } from "./itemRolls.js"

export const itemDefinitions = {
    great_sword0: {
        id: "great_sword0",
        name: "Stone Sword",
        type: "Weapon",
        kind: "Great Sword",
        icon: "/weapons/great_sword/stone_sword.png",
        rarity: "common",
        attackStyle: "Melee",
        baseStats: {
            power: 10,
            damage: 10,
            crit: 5,
        },
        upgradedStats: {
            damage: 10,
            crit: 5,
            damagePoints: 0,
            critPoints: 0,
        },
        maxLevel: 10,
        level: 1,
        currentXp: 190,
        nextLvlXp: 320,
        upgradePoints: 1,
        enchantmentIds: [],
    },

    great_sword1: {
        id: "great_sword1",
        name: "Sword",
        type: "Weapon",
        kind: "Great Sword",
        icon: "/weapons/great_sword/forged.png",
        rarity: "legendary",
        attackStyle: "Melee",
        baseStats: {
            power: 130,
            damage: 40,
            crit: 20,
        },
        upgradedStats: {
            damage: 10,
            crit: 5,
            damagePoints: 0,
            critPoints: 0,
        },
        maxLevel: 10,
        level: 1,
        currentXp: 190,
        nextLvlXp: 320,
        upgradePoints: 1,
        enchantmentIds: ["critical_hit", "chain_lightning"],
    },

    great_sword2: {
        id: "great_sword2",
        name: "Sword",
        type: "Weapon",
        kind: "Great Sword",
        icon: "/weapons/great_sword/ruby_sword.png",
        rarity: "exalted",
        attackStyle: "Melee",
        baseStats: {
            power: 130,
            damage: 40,
            crit: 20,
        },
        upgradedStats: {
            damage: 10,
            crit: 5,
            damagePoints: 0,
            critPoints: 0,
        },
        maxLevel: 10,
        level: 0,
        currentXp: 50,
        nextLvlXp: 240,
        upgradePoints: 0,
        enchantmentIds: ["critical_hit", "chain_lightning"],
    },

    great_sword3: {
        id: "great_sword2",
        name: "Sword",
        type: "Weapon",
        kind: "Great Sword",
        icon: "/weapons/great_sword/obsidian_sword2.png",
        rarity: "exalted",
        attackStyle: "Melee",
        baseStats: {
            power: 130,
            damage: 40,
            crit: 20,
        },
        upgradedStats: {
            damage: 10,
            crit: 5,
            damagePoints: 0,
            critPoints: 0,
        },
        maxLevel: 10,
        level: 3,
        currentXp: 480,
        nextLvlXp: 550,
        upgradePoints: 3,
        enchantmentIds: ["critical_hit", "chain_lightning"],
    },

    iron_helmet: {
        id: "iron_helmet",
        name: "Iron Helmet",
        type: "Armor",
        kind: "helmet",
        icon: "/armor/helmet/helmet.png",
        rarity: "epic",
        baseStats: {
            hp: 50,
            armor: 15,
            power: 130,
        },
        upgradedStats: {
            hp: 50,
            armor: 15,
            hpPoints: 0,
            armorPoints: 0,
        },
        maxLevel: 10,
        level: 0,
        currentXp: 100,
        nextLvlXp: 240,
        upgradePoints: 0,
        enchantmentIds: [],
    },

    iron_arms: {
        id: "iron_gauntlet",
        name: "Iron Gauntlet",
        type: "Armor",
        kind: "arms",
        icon: "/armor/arms/arms.png",
        rarity: "epic",
        baseStats: {
            hp: 50,
            armor: 15,
            power: 130,
        },
        upgradedStats: {
            hp: 50,
            armor: 15,
            hpPoints: 0,
            armorPoints: 0,
        },
        maxLevel: 10,
        level: 1,
        currentXp: 200,
        nextLvlXp: 240,
        upgradePoints: 1,
        enchantmentIds: [],
    },

    iron_chest: {
        id: "iron_chest",
        name: "Iron Chestplate",
        type: "Armor",
        kind: "chest",
        icon: "/armor/chest/chest.png",
        rarity: "epic",
        baseStats: {
            hp: 50,
            armor: 15,
            power: 130,
        },
        upgradedStats: {
            hp: 50,
            armor: 15,
            hpPoints: 0,
            armorPoints: 0,
        },
        maxLevel: 10,
        level: 0,
        currentXp: 100,
        nextLvlXp: 240,
        upgradePoints: 0,
        enchantmentIds: [],
    },

    iron_legs: {
        id: "iron_legs",
        name: "Iron Greaves",
        type: "Armor",
        kind: "legs",
        icon: "/armor/legs/legs.png",
        rarity: "epic",
        baseStats: {
            hp: 50,
            armor: 15,
            power: 130,
        },
        upgradedStats: {
            hp: 50,
            armor: 15,
            hpPoints: 0,
            armorPoints: 0,
        },
        maxLevel: 10,
        level: 0,
        currentXp: 100,
        nextLvlXp: 240,
        upgradePoints: 0,
        enchantmentIds: [],
    },

    infernal_fragment: {
        id: "infernal_fragment",
        name: "Infernal Fragment",
        type: "Material",
        icon: "/currency/test_material.png",
        rarity: "epic",
    },
} as const satisfies Record<string, ItemDefinition>;

export type ItemId = keyof typeof itemDefinitions;